### ISSUE TITLE
This is brilliant! What's the license?

### ISSUE THREAD

**Issue by crisdosaygo** [bubner/DosGames#1]

**Comment by bubner** [comment]
Hi!

This was one of my first projects, discovering how I can use APIs and frameworks to build little web apps. This project almost exclusively uses [js-dos](https://github.com/caiiiycuk/js-dos), so I am not reserving any rights to the actual emulation software. The little web selector to go with it is only a wrapper and is public domain.

Would strongly suggest checking out https://js-dos.com/, it's a really neat little framework!

**Comment by crisdosaygo** [comment]
Thanks! I Found that after. But I saw your personal site, and the quality of it convinced you must have been the designer of JS-DOS! ☺️

**Comment by bubner** [comment]
Haha, I'm flattered. I'll add some docs to the project disclaiming the licensing.
Have a brilliant day!
